---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owncast
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: owncast
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gabekangas/owncast
      tag: 0.0.7
    env:
      TZ: "America/Chicago"
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - host: "stream.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "stream.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: owncast-config-v1
    additionalVolumeMounts:
    - name: media-franxx
      mountPath: "/media-franxx"
      readOnly: true
    additionalVolumes:
    - name: media-franxx
      persistentVolumeClaim:
        claimName: nfs-media-franxx-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0300_10de.present
              operator: Exists
