# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:eeCI5cch1lOSotG2rg1iw+RJ25eGUNzYJw/dZCcx4RfZUknNI+Z72tZWgTkt547R3bpT7IxeOZmQYJ6/WFS1gJynbkzgE6zFHpHbgMkvIWYA4iecaKq+idH5dRvJ1YV+Z4mPoEVJG1XFggKVcpdOowmWZQ022822GpRXwt2/OoltsgSA2REVb37Un2tM6PZ9ofnF9hTlo5v3EfEM5wI/3JUfQQ==,iv:AkWZPzYB/+bHprHxmRHKSuLTlsLDw3f7jJkFBJd3Yxo=,tag:IwC0eN2tOlY7j8OXcnpazg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-11T23:27:44Z"
    mac: ENC[AES256_GCM,data:2z0BgAwz408+gSDfuxGtt75mF++qOSgKb/RGdm0fqTORrFB+a/Yc/alXS0NVOl43WAkxY8HpUozQooa6VhdA88OcoNFUUtz8uhpeymBj1t/xXL4gE85Be2FXmhGFHKOaIulgPIiRScwxvaYG4C289QjIHZ8T3E9ykiYnrl1/bQk=,iv:MehdXoE4gTDoF+mG9SRatebR8LHxoy+g+709/I+LHII=,tag:q97WqxBWqRHLmAekD9IzWw==,type:str]
    pgp:
        - created_at: "2021-08-11T16:45:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw1XfxK/K1q7AQ//W3HMMNXuYZ0ET4cezjUunygCWxtarUJVXngpjQ6bnLqd
            drG0E4aI/iLl6xk5S4cTIVeq9b19ygsoOxRbIR0BXKvZ+l8SL18fkt8eFytkcy6/
            fNNrlBXwdI1IqP2my7KZagMN4Ali5ULBGr+XK7Ggf4eG5e8LDY9x1anxVWfdrJ3N
            EAxWaAFScs8fh9M0NfbtZK/wyF/wSAarCFvQoJ8UqRd/IIMLnj/Ks5IiDxj/09fv
            QwP/4P1eOZKF5TfyIL1+EEdC9ZmXnM+E9sVRAm8NKz5gP/Mmtx4HcJa01TAtHFxq
            7i5N9uYaAQ1JRoqVtuGg4SKuqTqnGDKbhgnXNj0ESXC0GSBQ+GXLHLKTQLe+lxu7
            PSd88Kkyr8bFUTJxQvSigm0BoFcIapeO53qF9+3AeWm/A0lmJ/pABaSl17nmr+IM
            n5TcNrmHDvZS25Og2PPLHRKbBllbffe8/YhHv6Oi/STCyMeg+6IqdGvJ8I7tHfxy
            ISi00Gc+Z0Bdq+MCOK4OSQiX5oJpDDvJzVE38u2WRDG5xQyB6oStXvj/IoxGH5DR
            trWjVgQG4x+vTiPkfRCx2ZYKAeGLm3UK5RMbSbUu598KlmYZJ8aP9Yo/vku08HCB
            XjVA1zdjVGmIYx2SSn/EWHS2vaSJyGd45MVKjM6TJzyElRmyExUENQeuRBL4/5jS
            XAEp38n+q5FT/xI9yU5vxnrUwFUNnVT5JTiDdLRtdwA9vVM9C0vcjJ8FewujFoM6
            dJaqiZTe65RPRrtrPgBFHir++O4xPdJyGwhUtfniXzUTg35ajIpjPTfnHPnC
            =Kbhk
            -----END PGP MESSAGE-----
          fp: CABC84E79A7718BEBFBCD3C4AD11DC94E06CCA1B
        - created_at: "2021-08-11T16:45:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAySEZvKqXwiCAQ//QQszC7rRYuxGvKIE6ZN9aIIVLiRD5YeV2yNghgwpTrbd
            279piWAlrlRQhhoTJppQ+qBzLsK8wpUJnXuM8bMQ1oHj6E+gMIkGRFevC+m0of7t
            KLSjnm5dnle9pPGZMQVTxTfr1Cf7mv8CYLM+w+zFLOxgTEPQJKG5X5EhfoQb4hXR
            QKFxjSqJVzj3QQ6loufTwMPGEYhQ7P0Y1XPjJJs6aZiPNvGK/8ayNCQpRo3E7NF3
            KqEGsLHQGSEeuWoOhb6Mnike5rox6p4hb7TPl7JHZbCJIP2YwWd3ERGBfLL2pgCg
            RLLG/nZwucnxb7lGZRYMN8krGtcdRYKSD0FY9EPoVvQDZ3fGtkwkbBfT9kjD4XPg
            6NGKDrTY/FJTOMIhY0shRBmFx3KHi0dnBKrfBvXyaY4yzgafC5s1p6QooJXMz+Vp
            YtfzsiZIESwhfKRdiuZ/eeMYyAedeW2mEd2zZbAfw0QNM4bSWwtQ2Iogh96nwQDL
            2Nt8kN2J+YrUFiyCeECEreUUIlqvMxhymMou/FAFsUPYQXPdTYX5tvrls4AM5PcI
            AbYvat4R7du5CKNM6uU3pY/C2Ufam2oSiikQs8HuwT8UnJ1qHxN5N89jlkjL8Esf
            bZ+HiTLM+AXvnhnTdnSLUwCiXfEq8lBOrhYMuijdAu1b3AbVH0DxDk94rBndoo/S
            XAEaUggPJtMqmxuDudXnoM1vedLyTKJaBaOFh1S0koTgspw3tVotyxFZMkO3F8Wf
            TTznEnF/6+dyQ0du9q/ldyT34pP9JRVvQ24w+Fs7zvZM4kcUJSggOnMcqT58
            =oBkN
            -----END PGP MESSAGE-----
          fp: 0E883B2F1196288130061C6BA8B44BCF50372B6B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
