# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ext-gateway-vpnconfig
    namespace: ext-gateway
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:gsIU74jNgR4JRphs/BeJOiXYjxk9ILhIx3IJmsPi9pmsB052TssFcTF2VxgwaKg0XjrIMZ25UtxNy+0YF91IEFE85mPfdQIQUA4Hn0Ql6sitCGSL1BN2Jh6jlC9ddoVsxlSuFBmu9WTB6a3N4B+ewxwq8oOirSWa/treIvCtpHfnuMGbC5hU3sPEMIVeGo5Ws6I8kY24HyGjmqEGWCRpNyFw06CRJTm+mdwsyRXKSFgHOAobJr8wcVg5MpszwpB6cMskZlUo2UTpBX3PjJuKicCAh7v69Ta0hiZSKcYCajhR4c3Ij0zQw9+lbugS3oq+1DIN2GnAYh7cZJ5oKZJN/NmavZzTu89Ie84MTjeWrW9/bQPWjPC8bB9W/F0LqRGsqvsDoYGcAvlV4sl2uvuw1ngfqiexPP7cB2PboO3PyyIt,iv:BeuAVcIhYU65wuC+zXuhveEaGbmP92xfyjyun5pW+7s=,tag:v/lrrmzWX+wxD6/LEqnPDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-05T00:28:20Z"
    mac: ENC[AES256_GCM,data:1ulxBabn+jEMHNqxJN67/8com+5PXrSm45kYOQZQUXISL6QNN5cWXyzjIX18jzceseYB6H4dNd5O+dyvZx1/TJHKH0dVbweMkF8/k2g/YUHHjlcNCbzq/ZgDVu0sc4wOSyGAakfVOHWtNWFjLWkxe67jpQZ7KN9zHSdQnDKdmVs=,iv:MI+XGkRFqW/t2bXRpN/isC2XeWW15vBpopQ1QDNOtkY=,tag:/hXBBErzHQAuL4XSP/hFqg==,type:str]
    pgp:
        - created_at: "2021-05-23T04:25:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw1XfxK/K1q7AQ//d/yXAKPJqcIRrjmW8Ft3juKGcDfGfMBNcPreMCfY0L9M
            NgiRQ1TEfAJ50VI4B5DVotL3s+S/8CZEsnMd0xCmHLcZHsZH6CyoDzwlPaiMOCjV
            Cyy5xWg2iRa3YS0NYIogZgfXzDSrpTjblBynj9qLZjzUm+V/3utzcSN2zYjYx4jE
            C/tLN8a/oLQArH5NWPUBoKE+9OX90/DpdfwBti8nGqIlVgIKQ57hBFPfnu4Cfjtj
            B6K9clgxmNvIs6TIAIOpHD5hcG7oUuAhOChtJMSH+krVVnJnG/k5PK7rrGtQNUq5
            Zt2mKljW6FpmZkfqkoHIhIrnnQoJizJ9Mgab/Kw5m2p1CnJlfocvOt6u9YE80RUl
            5RaF9+eKtYhn9eTozhd31HogvykZcZ/SiZ/jHfgGy3x9HnCn8/mXanwoEnaSDwal
            AH7tAxD5+oDkpdyt37kyAhVEhtnhTjuS90pDpeOsyh4sWC/0Se/m3RYi//if5MUt
            pKhfsLq2fOTaL2pBMpmjN2s80CCqw5PDwlUCzKr8tOwPxR1TY9HogjZA9/x5xLVv
            tOxj06eoCFk5w5hsdfd1i/omc7T2p2IGP7myZ+iYTga9L0iVYdC3/32Th/XxFTMI
            td2HXZdPXvQXYoi9ft6NMUbgn129aL5rT7DI8DC8JhCIW3GYDLG3un1A8qMcBz3S
            XgFBREX39nBz3ZEa5Q7D9o/Q2zZ1VVw3srDnJUi2HyW4MoH6/iMlL5fhdUR0874K
            caJ37bJdIeavwoq28LYpzdl1H2siSmotHnWqpYo9V0BqBGbKMtBdsDAPgAj6CDo=
            =3ulM
            -----END PGP MESSAGE-----
          fp: CABC84E79A7718BEBFBCD3C4AD11DC94E06CCA1B
        - created_at: "2021-05-23T04:25:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAySEZvKqXwiCARAAiOusqNF8lAlCSDHsz5qFTspDoW3diCnl3tGRC2bNPxhu
            K+wfvmJzqQpd0Nn3lEhZ5SxpTorwBrDZePllmvSIwaMTVg47G+MUFUeTEH8EacUx
            4K2Nh11RgZppyM1C00cAiaytSVV5S8pNi/cizFJvGblc5sZiasFry8QsUVVD9fZm
            zf9i/OfHh1NOH1FpM7mE1UYiLofJaGM1ADtsGYlsZlsImeEGth9ZRWOOONeRl/r3
            Og8TG6yaPSjnu7WeC2yxO0fBqWE8dmYdQ8JXyDI/2ZsugiEJmdgR9KptzAWckjyY
            RSmu6G2pnIaYNDimzm7Tt/lqgpmN7HI/hjVC14Iv/amuzC620HmH4gefpR6Czvz3
            1bngkKQ0X3jAmDgROEUZpYv8F2MMipXsG3K89aicVdTXcBxfiiKk+2HTJWMZyk9E
            iy/JA9OMqjhRE6+hY7GbC+BFkRbIUw/Oe04DqWcY9LBQeJ1pnCZelzJosSc53peA
            l2kf1ff5mqvI4JsvO5ENM3HeXVGOYARhZqMPu9Vto4xhYNi1KKhi5I1TKhan+i5z
            2qsFy7AtXvDYghkMEROsyJqTZRcLMJwDrCU0B1R8YG2VOz/8+MI3F7qJrILDDiDb
            nezozUZOCOIEAklSz0UQAteWW0j/6lBytP6Yr3sMc0zg6/HSnHzLmU4eVioifYfS
            XgFOa7Ud91Unrgyf+SeupPJW0+rH1TNDBiOOSkWdGDBgkcWWngqz1qgnmf0xFYX0
            xUiRuTs8Goyp0slwxmFEHXiiWfrGsD+tdeYJWBWoxBm75wqiejfHEchln2saSEU=
            =c0ve
            -----END PGP MESSAGE-----
          fp: 0E883B2F1196288130061C6BA8B44BCF50372B6B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
