---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: networking
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "cloudflare@kubernetescrd"
spec:
  tls:
    - secretName: "${SECRET_DOMAIN/./-}-tls"
  rules:
    - host: s.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 443
---
kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: networking
spec:
  type: ExternalName
  externalName: s3.dfw1.${SECRET_DOMAIN}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: minio
  namespace: networking
spec:
  endpoints:
    - dnsName: "s.${SECRET_DOMAIN}"
      recordType: CNAME
      targets:
        - "ipv4.${SECRET_DOMAIN}"
