---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- botkube
- grafana
- kube-prometheus-stack
- loki
- promtail
# - snmp-exporter-switch-0
- snmp-exporter-ups-0
- speedtest-exporter
- thanos
#- unifi-poller
- uptimerobot-heartbeat
