---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cilium
- descheduler
- kube-cleanup-operator
- kured
- metrics-server
- node-feature-discovery
- node-problem-detector
- nvidia-device-plugin
- reloader
