---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 2.4.8
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: keycloak
    fullnameOverride: keycloak
    image:
      repository: bitnami/keycloak
      tag: 13.0.0-debian-10-r0
    auth:
      createAdminUser: true
      adminPassword: "${SECRET_KEYCLOAK_ADMIN_PASSWORD}"
      managementPassword: "${SECRET_KEYCLOAK_MANAGEMENT_PASSWORD}"
    proxyAddressForwarding: true
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hostname: "idp.${SECRET_DOMAIN}"
      tls: true
    postgresql:
      enabled: true
      postgresqlPassword: "${SECRET_KEYCLOAK_POSTGRES_PASSWORD}"
      persistence:
        enabled: true
        size: 10Gi