---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-franxx-pv
spec:
  storageClassName: downloads-franxx
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.75.30.15
    path: /tank/share
  mountOptions:
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-franxx-pvc
  namespace: downloads
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: downloads-franxx
  resources:
    requests:
      storage: 1Mi
