# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpnconfig
    namespace: media
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:QbqVpV5NFrkzh4St6XksEFYl6+/RYtE2MACPI2sMCwzUIJ9+qJLmkF1Fd0P+PVehaZWZVC5SbGGvSZMePKvgtIP08GWwy5rz4fef2aF5vrJ153JpyDK+SUhVqaYvMbLXim59qTAIsdLJiVsJi+UWC8QM6HyIP4ILb3FyZZCHTNoH04jCDPIHIlmBPleX3IQBe1M5h4grSb2Jg/SdiLwk4Qd7WwTe/cpyGjZRnvGNw1FOoCmk0iL2llgI2/JXggy6AuRsqbYQ/kfwgQ1XX7jtRcoDJNIBbHZqvu7J2sNa9XG0ASsat228bOb2z0Nks/SM+hn2NQv4ZzCbJ0iRHpTKnvhLXdQaYurjCJC1MRBbglpi+gk70WUfbFey5/effmyPFLdl/aBbGULnnXXnLsKEuOftsEX04Jx1BbtfwXrBs30P/sg1j6+eDP3osHPUOtmAPnvxo0uxxLm+H+Tn2WBzwiqlrwXe8/4N+ddkG+J7qz5FN7k=,iv:mT6BSaodcxf/sSsgne1rwdo/lBH3/5yS2xQr2rwpnN4=,tag:ksC5BMiyLQH2PzLK28PdOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-28T12:13:16Z"
    mac: ENC[AES256_GCM,data:599Ol6tUCXjzcZbBkV0vFOtP61s87wfbB+xcwJhwYJPLrDLoCwKuCw+TQrj/mtmVvUKaKROPvWNgMh8dG5bX8T/80Zz7OgwDKUqHe6MofHkEFlyG8Vu81AYNJgjPA5CTifWBgNI/2zqUvtvnpPyrTvQu/xlk2BFnSq1TeEooA7Y=,iv:76vXQ0KhGvoGoEBRJsP8YLqMML6uen9W6oSNr8IomfI=,tag:njGPApjYM4iOViNSmhDUag==,type:str]
    pgp:
        - created_at: "2021-05-23T04:27:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw1XfxK/K1q7AQ/9HUW0sFSYE38rqkHUo/X9EGajMt7ZaGvwgXfBFMItvb5w
            bY9GKuOHU1TJ5Kw0aRIucBDkODFWfDjpdmGN6ruznlUEIDF753ESR/qIg6o1LTih
            abre8KecmvjXCPGgrFpOntA+chfAPNU843wJSfUKv0rPfJiXNju5TBoH9qjrogA0
            sRdY51Wzn63wOHet3Gb3ui0PxvAKhRReVf4wjnLKaEz8mdoP7nCNzgHF0jpwoJwa
            U/OPoeRSSCFH7CV4zuOP7RMvAHRzAtZ56DlEIDor4xecHwbtEMbNcFLnXVwTBwzc
            U4mplTlrlIHKwuRhvuR47UogC8P/67vCdZ5REffgtOcR0pdMCTeOD+SxS2LErLcb
            8fN2KxcuEnqxp4/BbSuRBztLq5UNdD11VBybdwpovmfscsDtuA/wXCm3K6W1iBzw
            hYjmU6uDat1v0+0AMOlt/RXbhGq07uSZ2D5NO+hBPnrRBut4d5VbBl7jEgmc0G99
            BedPGXRD477J7ClfP+BfWAXfLNV9Rdmaf1yHGOLCH3Nn7opZYRCRZ0zKfOYAgFgI
            95Ni8gRj50EqfjUe3NfnoX4xYBsRoGd6isi+yvfmpyPCeeCprU3eKMgW1/qGuht2
            SJtyGy2QOEP5Zrc18Qx2kgXIla+C4Fg6nAQ6a6J0Q4XAPjNs23pDcMqv9uI00ZHS
            XgF8GIX49bSg9plm9vWivkFnmKEBv5cQxRhGF1fovi7G6cYp372C1q1e0vOWWDHT
            sUtIF9tyFztb2Uw3smh560Zsq2IdvrI4H9Q2lxgagR3QLJW4sE+5GzNg1WsmABU=
            =SwlK
            -----END PGP MESSAGE-----
          fp: CABC84E79A7718BEBFBCD3C4AD11DC94E06CCA1B
        - created_at: "2021-05-23T04:27:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAySEZvKqXwiCARAAho7OaR65yIzPGpyeqy2Y1q8r32z8Nk6yyza9gHL5wOAF
            e1n0mqt50GTHB+jZuCIGLQS6EzPl1WhjHp7bdxYPH9K/XafEG2kieU0sXYiGgxM2
            Xeouv9quXg6+A3r7dbX/w1w+pghn6YDmE+GKe+CSSqty7BKnDjjNTQ0RoZRtovjz
            Bs2qUhpTQWBaZMmWsM/F8tHu6MghGl++R9y0DqLKIFtthovokJSoy0ww7HQKvoFB
            1PZ1Pc0kfDYXnE83PVwYqS0nsWHvFJIt4N0raFRhyxMBrH+7Sf/qwoZRPu4qsF4p
            g5ybeeqPQcAwJnS+a7+HPnemU+wVcKqcGgvFaMKFL/DA/4ffpLLVHaM7vUBKndga
            NfOLlm6MyaUp40t5rs4/DWzrNLAwKKTwpz7Bdlu717k+WMRPkR2DHf3lfYSqziJs
            TnMAthH5UJy+9tNzPc0Mn9MwLqYpy2rZxwF9siViRVePtCLhh8dU6tikw9BrLkp/
            k/2zDl+Z/n0Ny58OTdDinyqCEAwiKDHhPkkJG3UHGd/wOUhHfoJPYc/2beg4vMbu
            SYA9fiTFjwz093Fvq9yIoHShZ25kRi6UkVxurVhnTY+XO4ipwbTqAthmj77oRnBS
            Bv3vOi6UDF2eXBLLwkNyY+JOH+XeHFR93jKFHzlSoU3trBUQYYL00/H2NOVJgkvS
            XgFNUPKPE4FE5T1pkxWvOT8rxWpV+IuCDBPNd4kmce+euIoJWzkSLTUp3ztEDB5o
            XDzLK7L1wpaldyeNsLErR5A1zNPIoQfQk3DfgkSZu87ZNxgxIEvR2YdQevjR/n8=
            =08Da
            -----END PGP MESSAGE-----
          fp: 0E883B2F1196288130061C6BA8B44BCF50372B6B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
