---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: vpa
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:
    recommender:
      enabled: true
      image:
        repository: us.gcr.io/k8s-artifacts-prod/autoscaling/vpa-recommender
        tag: 0.9.2
      extraArgs:
        prometheus-address: |
          http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        storage: prometheus
    updater:
      enabled: false
