---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - cronjob-pgbackup.yaml
- helm-release.yaml
- service-monitor.yaml
configMapGenerator:
- name: ceph-config
  files:
  - ceph/generate-ceph.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
