---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/jackett
      tag: v0.18.145
    env:
      TZ: "America/Chicago"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-auth@kubernetescrd"
      hosts:
      - host: "jackett.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "jackett.${SECRET_DOMAIN}"
    additionalIngresses:
    - enabled: true
      nameSuffix: "api"
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
      hosts:
      - host: "jackett.${SECRET_DOMAIN}"
        paths:
        - path: /api
          pathType: Prefix
      tls:
      - hosts:
        - "jackett.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: jackett-config-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1000Mi
    addons:
      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210424
        env:
          TZ: "America/Chicago"
          IPTABLES_BACKEND: legacy
          KILLSWITCH: "true"
          KILLSWITCH_EXCLUDEDNETWORKS_IPV4: ${NETWORK_K8S_CLUSTER_CIDR};${NETWORK_K8S_SERVICE_CIDR};${NETWORK_MANAGEMENT_CIDR}
        configFileSecret: jackett-vpnconfig
        scripts:
          up: |-
            #!/bin/bash
            echo "connected" > /shared/vpnstatus

          down: |-
            #!/bin/bash
            echo "disconnected" > /shared/vpnstatus
        resources:
          requests:
            cpu: "0.001"
            memory: 128Mi
          limits:
            memory: 512Mi
