---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    master-nodes:
      hosts:
        dfw-k8s-master1:
        dfw-k8s-master2:
        dfw-k8s-master3:
    # Node group, do not change the 'node' name
    # hosts should match the filenames in 'host_vars'
    worker-nodes:
      hosts:
        dfw-k8s-worker1:
        dfw-k8s-worker2:
        dfw-k8s-worker3:
        dfw-k8s-worker4:
    gpu-nodes:
      hosts:
        dfw-k8s-cuda1:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
        nas-franxx:
