---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: media-backup
  namespace: kasten-io
spec:
  frequency: "@daily"
  retention:
    daily: 14
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - media
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - resource: persistentvolumeclaims
        excludeResources:
        - resource: persistentvolumeclaims
          name: nfs-media-franxx-pvc
      profile:
        namespace: kasten-io
        name: nfs
  - action: export
    exportParameters:
      frequency: "@daily"
      migrationToken:
        name: media-backup-migration-token-2b2jw
        namespace: kasten-io
      profile:
        name: nfs
        namespace: kasten-io
      exportData:
        enabled: true
