# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kured-discord-secret
    namespace: kube-system
stringData:
    webhook: ENC[AES256_GCM,data:fCxlfMDvUsd1/yNbNTXFL7XovFhLx0nJ4nLYj6axVtUYiqVqDKKpnTrl/RzKotfqnIFPDi6kjgk0mYloMvDB1baHp5U4U25PGqK13EWxEW4Rv4NvqCLeK6jorRuMcBVA+ev/K5wVBTUHeVWB1otT9KrdCLgWzpowODmkbZe2nShXIuV1nw==,iv:bF5gQop7VlhSYB5Rp/ABp3xdQoCb/DYQRrsEbtZBdlI=,tag:PhPC8udFrSARz1R5FS+txQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-16T03:12:40Z"
    mac: ENC[AES256_GCM,data:vxP4H3m2q3Bxr6mf7KVU9iWx/49whZ9eYapFI0MrvjuNltSTKPGNlhqvtxuwq0Vu51/+LhO4F6m9JKkIRrWUbKKnYPXCV30MSUyZbPGLdG/9nq5n5wbwNnKOy39mM6d+KlcFKUgIAcp/pZMGiMiobGkiML60fAiysWMyS9Hji68=,iv:7PyP0N9YsxYC9Zp6FO4q6ay0twOsmkK+NwtsgjOB1p4=,tag:CvwHS7CAVG5E7KLxZPWs/w==,type:str]
    pgp:
        - created_at: "2021-05-16T03:12:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw1XfxK/K1q7ARAAiuZc0Vi2vFbhO92iCBWYPZUHANvmNhNf2ncKWO4pFZYX
            mopOMqA2w2DQuFrenF+bIsudKh0pyfE2tC4yhSQbPptSscSVJ9TqzYP6Ewp2No8X
            e4wStr8GQwy4HkRFwUJH1EpbbtkL8YegwnuJsvZwotSwlLc5t9f3fEY1oo/nvO1k
            WUmAC7+ib/huv12fVmFBoWQOqqQvyBNZzHbnhrgsZf0S0xvrw8euu4sNBtauMb5+
            W3FEJ1E7nP7TrKCblEtoLpL4krs18KltTS2s9NnjrSLW7G2PSkWqtu7t8GqhXrBE
            laTOJsD7id2KHiiyCWfeV6TDiw4pA0zf1Lodr/ZJbnrC4LIKm/3GAXsknWOyP6wY
            4OuZh6lbe+ZLQc+tRnUxBkdqDoG740Qrv+bz7B2aXGr96eyw1P92WTTQAPIKtUFq
            H3uUFJNPdLvZWq65erX6kHXdVSxfKWkQZJj6LB7u3JLkno729moia6dfqJSJaa9e
            aL68BK9bnCxkrkRKULSohKuHWYfaRJqoHUju4iEZQqoLioS336Pap8WJU67SWfoR
            5hzPTG5qhj5wjsCwK91ZjDa93mAvqCefpjY+aUQkOVMJyuWFC7K4UYheUyFRE38Z
            XRkouJVen/AJU1Dj0HHo90+VsonE95atr+VYRW6u/pq3cgNoY2NnvFMFK416b3PS
            XAFyycwL7XX38xsIZfnW3146P0FfF6kaIa1aS3kJDsPNZQw1TAqeBfP4eohXoVGT
            FQDi9vH1qhO69jsjEPoLZKiuh6mzSfQBbf/m9Iv4yUq1tdpg2LlJsBKwWGqi
            =yz9z
            -----END PGP MESSAGE-----
          fp: CABC84E79A7718BEBFBCD3C4AD11DC94E06CCA1B
        - created_at: "2021-05-16T03:12:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAySEZvKqXwiCAQ/9HbYit+0Wc9O8I9PkJRxDuOhmvMoXrbWhO1VDOWmJK4fr
            IEqP3zxsqOQ8fhxtfDAuhOzK6aV94cx9ZkzDafdjez6wk0wMBDPlVDv6zCS98yPi
            9AQF/psRUTC+LPx2EqsNnwSMD9lHublHRdoiSmcaeWnm1qEEeokAbyObD1n5V+C9
            U5PVhY1rcqqewHRc5s6vXy6AyTP838+hoBwPWyqrp3AdFwOYsDXzOa+5fsGfXtbZ
            +aNMNzhR47y2+qbbzCpsF3qNjM7eWQiNIm40/Ue/5lC5wEAzAbz4SIJkcqIxNNvu
            MaPiXYaxHRs2CWGlGEikPp+uxHT4jkhMVdyJTlC3KfKhKR2ozWzyIQML5GdcX/0Z
            b5QXHYGM4V1rv6VuW5/W+T12KSyAgvT1FdN6TwPdVwAWkDUJzQgFxaShR3r0AW5L
            EoVdLRq+zBq96USBrybTDO8C3gZ2LA82KdmO5vT7JDDhrBdIyLqdEvcCazRwWyV6
            DJPS7ZNPhwt+8RgQrWCd2a98KXdPHvzoi1R+n49OngzK3Pdl6yQbzoNqRO10/kPW
            0Y1f1Bbvca1gh1YpVQc48+c9RPfwxIs4NGqYjh8ayTlM8Cp1X7dy+RhnWWNpvWon
            yPoRvIwgmfjHN54Y5Qe7DKT7r1W4CoDcJ9bSAdQthLFQcIN77UOvRiV1oGtIy+nS
            XAFaC4A/lpALvgeKwK5xuTYWWvN241irVOOTfbIdXZcccffWTuV0iGpViIizbAJt
            4ZERscb6OuS/HpoO49pBYtIdyd9sNzjf42MP9MmKcta/iMrrVqJsvchWcCxq
            =BTAL
            -----END PGP MESSAGE-----
          fp: 0E883B2F1196288130061C6BA8B44BCF50372B6B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
