---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- _pvc
- airsonic
- flaresolverr
- jellyfin
- lidarr
- overseerr
- owncast
- plex
- prowlarr
- qbittorrent
- radarr
- sabnzbd
- sonarr
- tautulli
