---

- name: kube_vip | create k3s staticpod directory
  ansible.builtin.file:
    path: "{{ kube_vip.pod_manifests_dir }}"
    recurse: yes
    state: directory
    mode: 0644
  when:
  - k3s_control_node is defined
  - k3s_control_node

- name: kube_vip | deploy manifest to k3s staticpod directory
  ansible.builtin.template:
    src: "kube-vip.yaml.j2"
    dest: "{{ kube_vip.pod_manifests_dir }}/kube-vip.yaml"
    mode: 0644
  when:
  - k3s_control_node is defined
  - k3s_control_node
