---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funkwhale-data-v1
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
