---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funkwhale
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts/
      chart: funkwhale
      version: 0.3.10
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: funkwhale/funkwhale
      tag: 1.1.2
      pullPolicy: IfNotPresent
    database:
      host: funkwhale-postgresql
      user: postgres
      password: "${SECRET_FUNKWHALE_POSTGRES_PASSWORD}"
    djangoSecret: "${SECRET_FUNKWHALE_DJANGO_SECRET}"
    extraEnv:
      FUNKWHALE_PROTOCOL: https
    persistence:
      enabled: true
      existingClaim: funkwhale-data-v1
    ingress:
      enabled: true
      annotations:
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      host: "funk.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "funk.${SECRET_DOMAIN}"
    api:
      extraVolumeMounts:
      - name: media-franxx
        mountPath: /srv/funkwhale/data/music/media-franxx
        readOnly: true
      extraVolumes:
      - name: media-franxx
        persistentVolumeClaim:
          claimName: nfs-media-franxx-pvc
    front:
      extraVolumeMounts:
      - name: media-franxx
        mountPath: /srv/funkwhale/data/music/media-franxx
        readOnly: true
      extraVolumes:
      - name: media-franxx
        persistentVolumeClaim:
          claimName: nfs-media-franxx-pvc
    celery:
      worker:
        extraVolumeMounts:
        - name: media-franxx
          mountPath: /srv/funkwhale/data/music/media-franxx
          readOnly: true
        extraVolumes:
        - name: media-franxx
          persistentVolumeClaim:
            claimName: nfs-media-franxx-pvc
